server {
  host = "localhost"
  host = ${?HOST}

  port = 8082
  port = ${?PORT}

  #  Allowed origins of API requests
  allowedOrigins = ["http://localhost:3000"]
}

database {
  dataSourceClassName = org.h2.jdbcx.JdbcDataSource
  dataSource {
    url = "jdbc:h2:file:./userapp;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:h2-schema.sql'"
    user = sa
  }
  driver-class = "org.postgresql.Driver"
  # jdbc-parameters = ${JDBC_PARAMETERS}
  connections = {
    pool-size = 16
  }
}